<div align=center><h1>7.2 捕获异常</h1></div>


### 7.2.1 捕获异常

* 1、如果某个异常发生的时候没有在任何地方进行捕获，那程序就会终止执行，并在控制台上打印出异常信息，其中包括异常的类型和堆栈的内容。
* 2、要想捕获一个异常，必须设置 try/catch语句块。最简单的 try语句块如下所示：
  ```java
  try{
     code
     more code
     more code
  }catch (ExceptionTypee){
     handler for this type
  }
  ```
* 3、如果在 try语句块中的任何代码抛出了一个在 catch子句中说明的异常类，那么
	* 1)程序将跳过 try语句块的其余代码。
	* 2)程序将执行 catch 子句中的处理器代码。
* 4、如果在 try 语句块中的代码没有拋出任何异常，那么程序将跳过 catch子句。
* 5、如果方法中的任何代码拋出了一个在 catch子句中没有声明的异常类型，那么这个方法就会立刻退出（希望调用者为这种类型的异常设计了 catch子句)。
  ```java
  import java.io.IOException;

  public class FileFormatException extends IOException {
    public FileFormatException(){

    }

    public FileFormatException(String gripe){
        super(gripe);
    }
  }

  class TestExcetion{
    public void fun1() throws FileFormatException {
        throw new FileFormatException("抛出一个异常！");
    }

    public void fun2() {
        try {
            throw new FileFormatException("抛出一个异常！");
        } catch (FileFormatException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        TestExcetion testExcetion = new TestExcetion();
        try {
            testExcetion.fun1();
        } catch (FileFormatException e) {
            e.printStackTrace();
        }
    }
  }
  ```

* 6、编译器严格地执行 throws说明符。如果调用了一个抛出受查异常的方法，就必须对它进行处理，或者继续传递。
* 7、通常，应该捕获那些知道如何处理的异常，而将那些不知道怎样处理的异常继续进行传递。
* 8、如果想传递一个异常，就必须在方法的首部添加一个 throws说明符，以便告知调用者这个方法可能会抛出异常。
* 9、将异常直接交给能够胜任的处理器进行处理要比压制对它的处理更好。
* 10、如果编写一个覆盖超类的方法，而这个方法又没有抛出异常（如 JComponent中的 paintComponent), 那么这个方法就必须捕获方法代码中出现的每一个受查异常。**不允许在子类的 throws说明符中出现超过超类方法所列出的异常类范围**。


### 7.2.2 捕获多个异常

* 1、在一个 try语句块中可以捕获多个异常类型，并对不同类型的异常做出不同的处理。可以按照下列方式为每个异常类型使用一个单独的 catch子句：
  ```java
  try{
      code that might throw exceptions
  }catch (FileNotFoundException e){
      emergency action for missingfiles
  }catch (UnknownHostException e){
      emergency action for unknownhosts
  }catch (IOException e){
      emergency action for all other I/O problems
  }
  ```
* 2、异常对象可能包含与异常本身有关的信息。要想获得对象的更多信息，可以试着使用
  ```java
  e.getMessage()
  得到详细的错误信息（如果有的话)，或者使用
  e.getClass().getName()
   得到异常对象的实际类型。
  ```
* 3、捕获多个异常时，异常变量隐含为 final 变量。例如，不能在以下子句体中为 e 赋不同的值：
  ```java
  catch (FileNotFoundException | UnknownHostException e) { 
      . . . 
  }
  ```
* 4、捕获多个异常不仅会让你的代码看起来更简单，还会更高效。生成的字节码只包含一个对应公共 catch 子句的代码块。


### 7.2.3 再次抛出异常与异常链

* 1、在 catch 子句中可以抛出一个异常，这样做的目的是改变异常的类型。
* 2、下面给出了捕获异常并将它再次抛出的基本方法：
  ```java
  try{
       access the database
  }catch (SQLException e){
       throw new ServletException("database error: "+ e.getMessage());
  }
  ```
	* 这里，ServleException 用带有异常信息文本的构造器来构造。不过，可以有一种更好的处理方法，并且将原始异常设置为新异常的“ 原因”：
	  ```java
	  try{
          access the database
	  }catch (SQLException e){
          Throwable se=new ServletException("database error");
          se.initCause(e);
          throw se;
	  }
	  ```
	* 当捕获到异常时，就可以使用下面这条语句重新得到原始异常：
	  ```java
	  Throwable e = se.getCause();
	  ```
	* 强烈建议使用这种包装技术。这样可以让用户抛出子系统中的高级异常，而不会丢失原始异常的细节。
* 3、如果在一个方法中发生了一个受查异常，而不允许抛出它，那么包装技术就十分有用。我们可以捕获这个受查异常，并将它包装成一个运行时异常。
* 4、有时你可能只想记录一个异常，再将它重新抛出，而不做任何改变：
  ```java
  try{
     access thedatabase
  }catch (Exception e){
     logger.log(level, message, e);
     throw e;
  }
  ```

### 7.2.4 finally 子句

* 1、**当代码抛出一个异常时，就会终止方法中剩余代码的处理，并退出这个方法的执行**。
* 2、如果方法获得了一些本地资源，并且只有这个方法自己知道，又如果这些资源在退出方法之前必须被回收，那么就会产生资源回收问题。一种解决方案是捕获并重新抛出所有的异常。但是，这种解决方案比较乏味，这是因为需要在两个地方清除所分配的资源。一个在正常的代码中；另一个在异常代码中。
* 3、Java有一种更好的解决方案，这就是 finally 子句。
* 4、当发生异常时，恰当地关闭所有数据库的连接是非常重要的。
* 5、**不管是否有异常被捕获，finally 子句中的代码都被执行**。在下面的示例中，程序将在所有情况下关闭文件。
  ```java
  InputStream in = new FileInputStream(. . .);
  try{
      // 1
      codethatmightthrowexceptions
      // 2
  }catch (IOException e){
      // 3
      showerror message
      // 4
  }finally{
      // 5
      in.close();
  }
  // 6
  ```
* 6、在上面这段代码中，有下列 3 种情况会执行 finally 子句：
	* 1)代码没有抛出异常。在这种情况下，程序首先执行 try语句块中的全部代码，然后执行 finally 子句中的代码t 随后，继续执行 try语句块之后的第一条语句。也就是说，执行标注的 1、2、5、6处。
	* 2)抛出一个在 catch子句中捕获的异常。在上面的示例中就是 IOException异常。在这种情况下，程序将执行 try语句块中的所有代码，直到发生异常为止。此时，将跳过 try语句块中的剩余代码，转去执行与该异常匹配的 catch子句中的代码，最后执行 finally子句中的代码。
		* 如果 catch子句没有抛出异常，程序将执行 try 语句块之后的第一条语句。在这里，执行标注 1、3、4、5、6处的语句。
		* 如果 catch子句抛出了一个异常，异常将被抛回这个方法的调用者。在这里，执行标注1、3、5处的语句。
	* 3)代码抛出了一个异常，但这个异常不是由 catch 子句捕获的。在这种情况下，程序将执行 try语句块中的所有语句，直到有异常被抛出为止。此时，将跳过 try 语句块中的剩余代码，然后执行 finally子句中的语句，并将异常抛给这个方法的调用者。在这里，执行标注 1、5处的语句。
* 7、try语句可以只有 finally 子句，而没有 catch子句。例如，下面这条try语句：
  ```java
  InputStream in = . .
  try{
     code that might throw exceptions
  }finall{
     in.close();
  }
  ```
	* 无论在 try语句块中是否遇到异常，finally 子句中的 in.close()语句都会被执行。当然,如果真的遇到一个异常，这个异常将会被重新抛出，并且必须由另一个 catch 子句捕获。
* 8、事实上，我们认为在需要关闭资源时，用这种方式使用 finally子句是一种不错的选择。
* 9、强烈建议**解耦合 try/catch和 try/finally语句块**。这样可以提高代码的清晰度。例如：
  ```java
  InputStrean in = . . .;
  try{
     try{
          codethatmightthrowexceptions
     }finall{
          in.close();
     }
  }catch (IOException e){
     show error message
  }
  ```
	* 内层的try语句块只有一个职责，就是确保关闭输入流。外层的 try语句块也只有一个职责，就是确保报告出现的错误。这种设计方式不仅清楚，而且还具有一个功能，就是将会报告 finally 子句中出现的错误。
* 10、当 finally 子句包含 return语句时，将会出现一种意想不到的结果，假设利用 return语句从try语句块中退出。**在方法返回前，finally子句的内容将被执行。如果finally 子句中也有一个return语句，这个返回值将会覆盖原始的返回值**。请看一个复杂的例子：
  ```java
  public static int f(int n){
      try{
          int r = n * n;
          return r;
      }finally{
          if (n = 2) return 0;
      }
  }
  ```
	* 如果调用 f(2), 那么 try语句块的计算结果为 r=4, 并执行 return语句然而，在方法真正返回前，还要执行 finally 子句。finally子句将使得方法返回 0, 这个返回值覆盖了原始的返回值 4。
* 11、有时候，finally子句也会带来麻烦。例如，清理资源的方法也有可能抛出异常。假设希望能够确保在流处理代码中遇到异常时将流关闭。
  ```java
  InputStreai in = . .
  try{
     code that might throw exceptions
  }finally{
     in.closeO;
  }
  ```
	* 现在，假设在 try语句块中的代码抛出了一些非 IOException的异常，这些异常只有这个方法的调用者才能够给予处理。执行 finally语句块，并调用 dose方法。而 close方法本身也有可能抛出 IOException异常。当出现这种情况时，原始的异常将会丢失，转而抛出 close方法的异常。
	* 这会有问题，因为第一个异常很可能更有意思。如果你想做适当的处理，重新抛出原来的异常，代码会变得极其繁琐。如下所示：
	  ```java
	  InputStream in = .. .;
	  Exception ex = null;
	  try{
	       try{
               codethat might throw exceptions
	       }catch (Exception e){
	           ex = e;
	           throw e;
	       }
	  }finally{
           try{
	           in.close()；
	       }catch (Exception e){
	           if (ex = null) throw e;
	       }
	  }
	  ```

### 7.2.5 带资源的 try 语句

* 1、带资源的 try语句（try-with-resources) 的最简形式为：

  ```java
  try (Resource res = . . .){
       work with res
  }
  ```
	* try块退出时，会自动调用 res.doseO。下面给出一个典型的例子，这里要读取一个文件中的所有单词：
	
	  ```java
	  try (Scanner in = new Scanner(new FileInputStream("/usr/share/dict/words")), "UTF-8"){
	       while (in.hasNext())
	           System.out.println(in.next());
	  }
	  ```

	* 这个块正常退出时，或者存在一个异常时，都会调用in.close()方法，就好像使用了finally块一样。还可以指定多个资源: 例如：
	
	  ```java
	  try (Scanner in = new Scanne「(new FileInputStream("/usr/share/dict/words"), "UTF-8");PrintWriter out = new PrintWriter("out.txt")){
	      while (in.hasNextO)
	           out.println(in.next().toUpperCase());
	  }
	  ```

	* 不论这个块如何退出，in和 out 都会关闭。如果你用常规方式手动编程，就需要两个嵌套的 try/finally语句。
* 2、带资源的 try语句自身也可以有 catch 子句和一个 finally 子句。这些子句会在关闭资源之后执行。不过在实际中，一个 try语句中加入这么多内容可能不是一个好主意。

### 7.2.6 分析堆栈轨迹元素

* 1、**堆栈轨迹（ stack trace)** 是一个方法调用过程的列表，它包含了程序执行过程中方法调用的特定位置前面已经看到过这种列表，当 Java 程序正常终止，而没有捕获异常时，这个列表就会显示出来。
* 2、可以调用 Throwable 类的 printStackTrace 方法访问堆栈轨迹的文本描述信息
  ```java
  Throwable t = newThrowable();
  StringWriter out = new StringWriter();
  t.printStackTrace(new PrintWriter(out));
  String description = out.toString();
  ```
* 3、一种更灵活的方法是使用 getStackTrace 方法，它会得到 StackTraceElement 对象的一个数组，可以在你的程序中分析这个对象数组。例如：
  ```java
  Throwable t = new Throwable();
  StackTraceElement[] frames = t.getStackTrace();
  for (StackTraceElement frame : frames)
      analyze frame
  ```
	* StackTraceElement 类含有能够获得文件名和当前执行的代码行号的方法，N时，还含有能够获得类名和方法名的方法。toString 方法将产生一个格式化的字符串，其屮包含所获得的信息。
* 4、静态的 Thread.getAllStackTrace 方法，它可以产生所有线程的堆栈轨迹. 下面给出使用这个方法的具体方式：
  ```java
  Map<Thread, StackTraceElement[]> map = Thread.getAl1StackTraces();
  for (Thread t : map.keySet()){
      StackTraceElement[] frames = map.get(t);
      analyze frames
  }
  ```








































































































